### ISSUE TITLE
Documentation website has a 404

### ISSUE THREAD

**Issue by IHaveAVest** [FallingColors/HexMod#553]
The documentation page just shows a 404 whenever I try to open it.

**Comment by object-Object** [comment]
Thanks for the report! This is actually expected (though a bit unfortunate). From the announcement on Discord:

> The old web book link (https://gamma-delta.github.io/HexMod) broke when the mod was moved to the FallingColors org. You can find that book at https://fallingcolors.github.io/HexMod, or preview the new hexdoc book at https://hexcasting.hexxy.media/v/0.10.3.

**Comment by tizu69** [comment]
old issue, I doubt this still applies, but was pinned, so maybe?

would it be benefitial to bootstrap a simple repo that is just a static page telling you the wiki moved?

**Comment by object-Object** [comment]
Creating a new repo `gamma-delta/HexMod` would break the current behaviour where https://github.com/gamma-delta/HexMod redirects properly to https://github.com/FallingColors/HexMod, possibly also breaking people's local Git repos if they're still pointing at the old url. I think it's probably fine as-is, especially since the new book shows up on Google.

![Image](https://github.com/user-attachments/assets/64cd71ec-30f1-4758-b092-3fb1027c39e5)
