### ISSUE TITLE
[1.20.1] - Mod Incompatibility List

### ISSUE THREAD

**Issue by ToxinZangoose** [FallingColors/HexMod#572]
Hello,

I've compiled a list of mods that do not work either with hex casting or paucal.

Here are the mods and the issues that they have caused together with Hex and Paucal and its dependencies.

Applied Energistics 2: Issue during mod loading, caused by a throwable error. Issue was resolved after removing AE2.

Apotheosis: No real way to use Apotheosis with Hex anyway, simply an addon for my modpack.

Create: Issue is similar to AE2's, but this time it had to do with flywheel having difficulties working alongside Hex and Paucal.

Titanium/BDLib: Dependencies for Industrial Foregoing and Functional Storage, couldn't launch because of similar troubles.

Note that this is the pre release versions of Paucal and Hex, I suppose these will be fixed either through the mentioned mod's developers or from Hex's developers.

Thank you for your time, I look forward to seeing the future of Hex Casting and its addons.

**Comment by ToxinZangoose** [comment]
I have also compiled the logs for the mods mentioned above:
Here are the logs:
[crash-2024-01-03_19.34.46-fml.txt](https://github.com/FallingColors/HexMod/files/13825214/crash-2024-01-03_19.34.46-fml.txt)
[crash-2024-01-03_19.37.01-fml.txt](https://github.com/FallingColors/HexMod/files/13825215/crash-2024-01-03_19.37.01-fml.txt)
[crash-2024-01-03_19.39.01-fml.txt](https://github.com/FallingColors/HexMod/files/13825216/crash-2024-01-03_19.39.01-fml.txt)
[crash-2024-01-03_19.46.22-client.txt](https://github.com/FallingColors/HexMod/files/13825217/crash-2024-01-03_19.46.22-client.txt)
[crash-2024-01-03_19.47.14-client.txt](https://github.com/FallingColors/HexMod/files/13825218/crash-2024-01-03_19.47.14-client.txt)
[crash-2024-01-03_19.58.57-client.txt](https://github.com/FallingColors/HexMod/files/13825219/crash-2024-01-03_19.58.57-client.txt)
[crash-2024-01-03_19.11.50-client.txt](https://github.com/FallingColors/HexMod/files/13825220/crash-2024-01-03_19.11.50-client.txt)
[crash-2024-01-03_19.15.28-fml.txt](https://github.com/FallingColors/HexMod/files/13825221/crash-2024-01-03_19.15.28-fml.txt)
[crash-2024-01-03_19.15.58-fml.txt](https://github.com/FallingColors/HexMod/files/13825222/crash-2024-01-03_19.15.58-fml.txt)
[crash-2024-01-03_19.19.03-client.txt](https://github.com/FallingColors/HexMod/files/13825223/crash-2024-01-03_19.19.03-client.txt)
[crash-2024-01-03_19.30.18-fml.txt](https://github.com/FallingColors/HexMod/files/13825224/crash-2024-01-03_19.30.18-fml.txt)


Tested on Forge 47.2.0, Minecraft 1.20.1 using PrismLauncher

**Comment by macks2008** [comment]
I'm going to see if I can narrow down the conflicts here when I have some time. (Really looking forward to adding Hex and Hexal to ATM 9 once they are ready, even if I only get the worldgen at first. So I want to help move things along)

**Comment by vgskye** [comment]
I was able to launch and join a world in ATM9 0.3.0 with Hex pre-651 present.
Here's my analysis of the logs:
[crash-2024-01-03_19.34.46-fml.txt](https://github.com/FallingColors/HexMod/files/13825214/crash-2024-01-03_19.34.46-fml.txt): Advanced Generators requiring Scalable Cat's Force, which is missing.
[crash-2024-01-03_19.37.01-fml.txt](https://github.com/FallingColors/HexMod/files/13825215/crash-2024-01-03_19.37.01-fml.txt): Anvil Restoration requiring Collective, which is missing.
[crash-2024-01-03_19.39.01-fml.txt](https://github.com/FallingColors/HexMod/files/13825216/crash-2024-01-03_19.39.01-fml.txt): Cyclic requiring FLIB, which is missing.
[crash-2024-01-03_19.46.22-client.txt](https://github.com/FallingColors/HexMod/files/13825217/crash-2024-01-03_19.46.22-client.txt): A ForgeMixinDatagenModLoader issue, offending code had unclear purpose and was removed in #706.
[crash-2024-01-03_19.47.14-client.txt](https://github.com/FallingColors/HexMod/files/13825218/crash-2024-01-03_19.47.14-client.txt): A ForgeMixinDatagenModLoader issue, offending code had unclear purpose and was removed in #706.
[crash-2024-01-03_19.58.57-client.txt](https://github.com/FallingColors/HexMod/files/13825219/crash-2024-01-03_19.58.57-client.txt): Seems to be... Solar Flux Reborn trying to add an item group after forge's registry freeze? I can't see any relation with Hex.
[crash-2024-01-03_19.11.50-client.txt](https://github.com/FallingColors/HexMod/files/13825220/crash-2024-01-03_19.11.50-client.txt): A ForgeMixinDatagenModLoader issue, offending code had unclear purpose and was removed in #706.
[crash-2024-01-03_19.15.28-fml.txt](https://github.com/FallingColors/HexMod/files/13825221/crash-2024-01-03_19.15.28-fml.txt): Hex Casting requiring Kotlin for Forge, which is missing.
[crash-2024-01-03_19.15.58-fml.txt](https://github.com/FallingColors/HexMod/files/13825222/crash-2024-01-03_19.15.58-fml.txt): Hex Casting requiring Patchouli, which is missing.
[crash-2024-01-03_19.19.03-client.txt](https://github.com/FallingColors/HexMod/files/13825223/crash-2024-01-03_19.19.03-client.txt): Hex Casting requiring Caelus API, which is missing. This fails with a slightly unintuitive error since Caelus wasn't defined as a dependency in mods.toml, but that was fixed in #681.
[crash-2024-01-03_19.30.18-fml.txt](https://github.com/FallingColors/HexMod/files/13825224/crash-2024-01-03_19.30.18-fml.txt): Enchanting Infuser requiring Puzzles Lib, which is missing.

All of them seems to be either completely unrelated to Hex or PAUCAL, missing dependencies, or was fixed in #706. Thus, I believe this issue no longer represents an actual issue and can be closed.

**Comment by object-Object** [comment]
Thanks for the analysis!
