### ISSUE TITLE
edifying a tree does not work

### ISSUE THREAD

**Issue by bzzzzzzzzzzzzzzzzzzzzzzzzz** [FallingColors/HexMod#574]
edifying a tree executes successfully but the sapling remains unchanged.

**Comment by Alchristis** [comment]
hexcasting-fabric-1.20.1-0.11.1-7-pre-609 and hexcasting-forge-1.20.1-0.11.1-7-pre-609
As original post states, the spell executes when given a sapling's coordinates, yet doesn't do anything to the sapling.

**Comment by dashkal16** [comment]
I spent some time poking at this one.  It fails because the edified trees are never registered as `ConfiguredFeature<?,?>`s.

However, simply trying to register them in the same manner as other registered objects failed.
On Forge, the registration method never got called.  On fabric, there is no `BuiltInRegistries.CONFIGURED_FEATURE`

**Comment by dashkal16** [comment]
Potential fix submitted as PR #594 .
I'm not happy with that solution, but it does serve to demonstrate exactly what's wrong.
