### ISSUE TITLE
Invalid entry is written to `#minecraft:mineable/pickaxe` tag

### ISSUE THREAD

**Issue by MrRain139** [FallingColors/HexMod#664]
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

0.11.1-7

### Modloader version

Forge 37.1.3

### Issue description

The mod writes an invalid entry in the minecraft:mineable/pickaxe tag and because of this the whole tag is cleared.

### Steps to reproduce

1 install the mod
2 run

**Comment by SamsTheNerd** [comment]
do you have a log for this? I can't reproduce it in the latest version. 

Either was fixed at some point or caused by another mod (I know sometimes this bug can look like other mods are causing it when they're actually just being effected by it)

**Comment by ZenDev20** [comment]
From my testing, this is an issue caused by Ducky Peripherals when used with Hex Casting. When I took out Ducky Peripherals pickaxes worked as usual, and when it put the mod back in they stopped working and threw the error below when loading into the world.

I checked the page for Ducky Peripherals and they are aware of and have fixed the issue recently, but an update isn't released yet.

Versions:
- Forge: 47.3.0
- Hex Casting: 0.11.2
- Ducky Peripherals: 1.20.1-1.3.1

```
[Worker-ResourceReload-6/ERROR] [minecraft/TagLoader]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: ducky-periphs:focal_link_block (from duckyperiphs-1.20.1-1.3.1-forge.jar)
[Worker-ResourceReload-10/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:ducky-periphs:blocks/focal_link_block
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'ducky-periphs:focal_link_block'
```
